[package]
distribution = "2201.0.0"
org = "ballerinax"
name = "twitter"
license= ["Apache-2.0"]
authors = ["Ballerina"]
version= "2.2.0"
export= ["twitter", "twitter.listener"]
repository = "https://github.com/ballerina-platform/module-ballerinax-twitter"
keywords = ["Marketing/Social Media Accounts", "Cost/Freemium"]
icon = "icon.png"

[build-options]
observability-included=true

[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-2.2.0.jar"
groupId = "org.ballerinalang.twitter"
artifactId = "java-wrapper"
version = "2.2.0"
