[package]
distribution = "2201.7.0"
org = "ballerinax"
name = "twitter"
license= ["Apache-2.0"]
authors = ["Ballerina"]
version= "3.3.0"
export= ["twitter", "twitter.listener"]
repository = "https://github.com/ballerina-platform/module-ballerinax-twitter"
keywords = ["Marketing/Social Media Accounts", "Cost/Freemium"]
icon = "icon.png"

[build-options]
observability-included=true

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-3.3.0.jar"
groupId = "org.ballerinalang.twitter"
artifactId = "java-wrapper"
version = "3.3.0"
